--P1 - As part of this assignment, we need to list down all the entities, their attributes and the table structures for the scenario mentioned in the previous slide. You also need to write the SQL queries required to create these tables 
--along with few sample entries. Ensure the tables follow 1NF, 2NF, 3NF and BCNF rules.
--Table to add the movie details
CREATE TABLE MOVIE_DETAILS (
    MOVIE_ID NUMBER(12) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MOVIE_NAME VARCHAR2(50),
    LNG VARCHAR2(5),
    SCREEN_TYPE VARCHAR2(5),
    MOVIE_EE VARCHAR2(5)
);

--Table to add theatre table
CREATE TABLE THEATRE (
    THEATRE_ID NUMBER(12) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    THEATRE_NAME VARCHAR(50),
    ADDRESS_1 VARCHAR2(20),
    STREET VARCHAR2(20),
    POSTAL VARCHAR2(8),
    CITY VARCHAR(20),
    STATE VARCHAR(20)
);

--table to map the movie and theatre with active/inactive movi
CREATE TABLE AVAIL_MOVIE(
    THEATRE_ID NUMBER(12),
    MOVIE_ID NUMBER(12),
    IS_ACTIVE VARCHAR(2),
    CONSTRAINT FK_AV_MOVIE  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE_DETAILS(MOVIE_ID),
    CONSTRAINT FK_AV_THEATRE FOREIGN KEY (THEATRE_ID) REFERENCES THEATRE(THEATRE_ID),
    CONSTRAINT PK_AV_MOVIE PRIMARY KEY (MOVIE_ID, THEATRE_ID)
);

--Movie Slots
CREATE TABLE MOVIE_SLOT (
    MOVIE_ID NUMBER(12),
    THEATRE_ID NUMBER(12),
    SLOT_DATE DATE,
    SLOT_TIME TIMESTAMP,
    CONSTRAINT FK_MOVIE  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE_DETAILS(MOVIE_ID),
    CONSTRAINT FK_THEATRE FOREIGN KEY (THEATRE_ID) REFERENCES THEATRE(THEATRE_ID),
    CONSTRAINT PK_SLOT PRIMARY KEY (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
);


INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Inception', 'EN', 'IMAX', 'UA');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Baahubali', 'TE', '2D', 'U');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Jawan', 'HI', '3D', 'UA');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Avatar 2', 'EN', '3D', 'U');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('KGF', 'KA', '2D', 'UA');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Pathaan', 'HI', '2D', 'UA');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Titanic', 'EN', '2D', 'U');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Pushpa', 'TE', '2D', 'UA');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('The Dark Knight', 'EN', 'IMAX', 'U');
INSERT INTO MOVIE_DETAILS (MOVIE_NAME, LNG, SCREEN_TYPE, MOVIE_EE)
VALUES ('Dangal', 'HI', '2D', 'U');

INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (2, 3, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (2, 4, 'N');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (3, 5, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (4, 6, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (4, 7, 'N');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (5, 8, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (6, 9, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (7, 10, 'N');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (8, 1, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (9, 2, 'N');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (10, 3, 'Y');
INSERT INTO AVAIL_MOVIE (THEATRE_ID, MOVIE_ID, IS_ACTIVE) VALUES (10, 4, 'Y');

INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES
(1, 1, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_TIMESTAMP('10:00:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(2, 2, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_TIMESTAMP('13:00:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(3, 3, TO_DATE('2025-08-10', 'YYYY-MM-DD'), TO_TIMESTAMP('16:30:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(4, 4, TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_TIMESTAMP('14:45:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(5, 5, TO_DATE('2025-08-11', 'YYYY-MM-DD'), TO_TIMESTAMP('19:00:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(6, 6, TO_DATE('2025-08-12', 'YYYY-MM-DD'), TO_TIMESTAMP('10:15:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(7, 7, TO_DATE('2025-08-12', 'YYYY-MM-DD'), TO_TIMESTAMP('12:00:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(8, 8, TO_DATE('2025-08-13', 'YYYY-MM-DD'), TO_TIMESTAMP('15:00:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(9, 9, TO_DATE('2025-08-13', 'YYYY-MM-DD'), TO_TIMESTAMP('18:30:00', 'HH24:MI:SS'));
INSERT INTO MOVIE_SLOT (MOVIE_ID, THEATRE_ID, SLOT_DATE, SLOT_TIME)
VALUES(10, 10, TO_DATE('2025-08-13', 'YYYY-MM-DD'), TO_TIMESTAMP('21:00:00', 'HH24:MI:SS'));


SELECT * FROM MOVIE_DETAILS;
SELECT * FROM THEATRE;
SELECT * FROM MOVIE_SLOT;
SELECT * FROM AVAIL_MOVIE;

//Update the city and state for all the theatre
UPDATE THEATRE SET CITY = 'BLR', STATE='KA';

SELECT * FROM THEATRE TH, AVAIL_MOVIE AM
WHERE TH.THEATRE_ID = AM.THEATRE_ID
AND TH.POSTAL = '560025'
AND IS_ACTIVE = 'Y';

--P2 - Write a query to list down all the shows on a given date at a given theatre along with their respective show timings.
SELECT
    TH.THEATRE_NAME,
    TH.CITY,
    TH.POSTAL,
    MD.MOVIE_NAME,
    MD.LNG,
    MD.SCREEN_TYPE,
    MD.MOVIE_EE,
    MS.SLOT_DATE,
    MS.SLOT_TIME
FROM
    MOVIE_SLOT MS,
    MOVIE_DETAILS MD,
    THEATRE       TH
WHERE
        MS.MOVIE_ID = MD.MOVIE_ID
    AND MS.THEATRE_ID = TH.THEATRE_ID
    AND MS.SLOT_DATE = '10-08-2025';








